# Use the official Dionaea Docker image
# FROM dinotools/dionaea-docker
FROM dinotools/dionaea:0.11.0
# FROM dinotools/dionaea:lates
COPY ./dionaea.cfg /opt/dionaea/etc/dionaea/dionaea.cfg
COPY ./ftp.yaml /opt/dionaea/etc/dionaea/services-enabled/

