version: '3'
services:
  alpine-ftp-server:
    ports:
      - '21:21'
      - '21000-21010:21000-21010'
    environment:
      - USERS: "one|123456"
      - ADDRESS: ftp.site.domain
    image: 'delfer/alpine-ftp-server:latest'