apiVersion: apps/v1
kind: Deployment
metadata:
  name: dionaea-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dionaea
  template:
    metadata:
      labels:
        app: dionaea
    spec:
      hostNetwork: true
      initContainers:                  
      - name: create-log-directory
        image: busybox
        command: ["sh", "-c", "mkdir -p /opt/dionaea/var/log/dionaea && mkdir -p /opt/dionaea/var/dionaea/roots/ftp && touch /opt/dionaea/var/log/dionaea/dionaea.log /opt/dionaea/var/dionaea/dionaea-errors.log && mkdir -p /opt/dionaea/config"]
        volumeMounts:
        - name: log-volume
          mountPath: /opt/dionaea/var/log/dionaea
          # mountPath: /opt/

      containers:
      - name: dionaea
        # image: dinotools/dionaea
        image: blackhatch/dionaea:master
        command: ["/bin/sh"]
        args: ["-c", "sleep infinity"]
        resources:
          limits:
            memory: "256Mi"
            cpu: "100m"
          requests:
            memory: "128Mi"
            cpu: "50m"
        volumeMounts:
        - name: log-volume
          mountPath: /opt/dionaea/var/log/dionaea
        - name: config-volume
          mountPath: /opt/dionaea/config
      volumes:
      - name: log-volume
        emptyDir: {}
      - name: config-volume
        configMap:
          name: dionaea-config  