apiVersion: apps/v1
kind: Deployment
metadata:
  name: dionaea-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: honeypot
  template:
    metadata:
      labels:
        app: honeypot
    spec:
      containers:
      - name: honeypot 
        image: 042347303331.dkr.ecr.eu-west-1.amazonaws.com/honeypot-project-y25ek2lf:latest
        resources:
          limits:
            memory: "256Mi"
            cpu: "100m"
          requests:
            memory: "128Mi"
            cpu: "50m"

