apiVersion: v1
kind: ConfigMap
metadata:
  name: dionaea-config
data:
  dionaea.cfg: |
    modules=curl,python,emu
 
    [logging]
    default.filename = var/log/dionaea/dionaea.log
    default.levels = all,-debug
    default.domains=*

    errors.filename = var/log/dionaea/dionaea-errors.log
    errors.levels=warning,error
    errors.domains=*

    [modules]
    # Enable HTTP service module
    http = yes
